### ISSUE TITLE
Windows version of libuvc

### ISSUE THREAD

**Issue by alexivaner** [node-ffi-libraries/node-ffi-library-libuvc-v0.0.6#1]
Hi, do you have Windows version of this libuvc? I got some errors when running the example of UVC (display-details). Thank you.

```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'D:\Kerja\Octon\ptzExample2\node_modules\@ffi-libraries\libuvc-v0.0.6\platforms\windows-x86_64\index.js'
Require stack:
- D:\Kerja\Octon\ptzExample2\node_modules\@ffi-libraries\libuvc-v0.0.6\index.js
- D:\Kerja\Octon\ptzExample2\node_modules\uvc\src\device.js
- D:\Kerja\Octon\ptzExample2\node_modules\uvc\src\context.js
- D:\Kerja\Octon\ptzExample2\node_modules\uvc\src\index.js
- D:\Kerja\Octon\ptzExample2\node_modules\uvc\index.js
- D:\Kerja\Octon\ptzExample2\node_modules\uvc\examples\display-details\display-details.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (D:\Kerja\Octon\ptzExample2\node_modules\@ffi-libraries\libuvc-v0.0.6\index.js:60:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (D:\Kerja\Octon\ptzExample2\node_modules\uvc\src\device.js:22:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Kerja\\Octon\\ptzExample2\\node_modules\\@ffi-libraries\\libuvc-v0.0.6\\index.js',
    'D:\\Kerja\\Octon\\ptzExample2\\node_modules\\uvc\\src\\device.js',
    'D:\\Kerja\\Octon\\ptzExample2\\node_modules\\uvc\\src\\context.js',
    'D:\\Kerja\\Octon\\ptzExample2\\node_modules\\uvc\\src\\index.js',
    'D:\\Kerja\\Octon\\ptzExample2\\node_modules\\uvc\\index.js',
    'D:\\Kerja\\Octon\\ptzExample2\\node_modules\\uvc\\examples\\display-details\\display-details.js'
  ]
}
```

**Comment by joelpurra** [comment]
@alexivaner: duplicate of your issue https://github.com/joelpurra/node-uvc/issues/1.

Keeping open for now, as it is unresolved until Conan has support for libuvc on Windows.
